<h1>MY Posts</h1>

 <?php
$this->gettest();

?>

<ul class="bxslider">
	<li><a class="fancybox" href="<?php echo $this->getSkinUrl('images/image.jpg') ?>"><img alt="example1" src="<?php echo $this->getSkinUrl('images/image.jpg') ?>" /></a></li>
	<li><a class="fancybox" href="<?php echo $this->getSkinUrl('images/image.jpg') ?>"><img alt="example1" src="<?php echo $this->getSkinUrl('images/image.jpg') ?>" /></a></li>
	<li><a class="fancybox" href="<?php echo $this->getSkinUrl('images/image.jpg') ?>"><img alt="example1" src="<?php echo $this->getSkinUrl('images/image.jpg') ?>" /></a></li>
	<li><a class="fancybox" href="<?php echo $this->getSkinUrl('images/image.jpg') ?>"><img alt="example1" src="<?php echo $this->getSkinUrl('images/image.jpg') ?>" /></a></li>
	<li><a class="fancybox" href="<?php echo $this->getSkinUrl('images/image.jpg') ?>"><img alt="example1" src="<?php echo $this->getSkinUrl('images/image.jpg') ?>" /></a></li>
</ul>